baseURL = 'https://danielims.github.io/kuramoto-cicada/'
languageCode = 'en-us'
title = 'Kuramoto Cicada Documentation'
theme = "hugo-theme-learn"
publishDir = "../docs"

[params]
landingPageURL='https://danielims.github.io/kuramoto-cicada/'
disableLandingPageButton = true

[Languages]
[Languages.en]
landingPageURL = "/kuramoto-cicada"
landingPageName = "<i class='fas fa-home'></i> Redirect to Home"
